### ISSUE TITLE
SaaS Portal sale shop flow

### ISSUE THREAD

**Issue by cmsalmeida** [it-projects-llc/odoo-saas-tools#102]
The shop sale flow is not straight, from start to creation of client database. The way it is requires client to remember to go back to shop at some point to finish process.
I've done [a drawing explaining that](https://docs.google.com/drawings/d/17ciP8YgmHV35Ro8Xh98nypWEa0IxlNmz7RDfiArp5B8/edit?usp=sharing).
I'll create a WIP PR...

**Comment by yelizariev** [comment]
It works in different way. 
After purchasing user receives email with links to create new database ( /page/start?plan_id=123 ) if he doesn't have database already

**Comment by yelizariev** [comment]
@iledarn

**Comment by cmsalmeida** [comment]
Even in that case then, user should not be redirected to database, instead should continue checkout till the end.

**Comment by yelizariev** [comment]
Try to use saas_portal_sale without saas_portal_signup. Ones could be inconsistent with each other.
