### ISSUE TITLE
Multiple Log In Session Expired

### ISSUE THREAD

**Issue by ghost** [it-projects-llc/odoo-saas-tools#120]
Hello,

Two different people are not allowed to enter client db using same OAuth.

One of the sessions gets expired.

However if we give a password to the user and enter without using OAuth this doesn't happen.

Best regards,

**Comment by yelizariev** [comment]
To use multiple login you have to have different logins at SaaS POrtal. That is each user has own oauth key

**Comment by ghost** [comment]
Understood. Thanks
