### ISSUE TITLE
[9.0] Traceback on installation of saas_portal_start

### ISSUE THREAD

**Issue by abhayvyas** [it-projects-llc/odoo-saas-tools#126]
I get this error when i try to install saas_portal_start module
![saas_portal_start](https://cloud.githubusercontent.com/assets/16646042/12233270/d4125886-b88b-11e5-9039-8de82daee125.png)

**Comment by yelizariev** [comment]
you try to install  8.0 branch on odoo 9.0

**Comment by abhayvyas** [comment]
I recheck code & i am confirming it's 9.0 branch with revision no 0af798efba0541012b2e3f0a405c4b61730bfc3c .
For more info if i would have tried to install with 8.0 branch it stops me at saas_portal installation & the traceback would be as below.
![traceback with branch 8_0](https://cloud.githubusercontent.com/assets/16646042/12234255/ac66693e-b891-11e5-9732-fed7a5b9c64d.png)

**Comment by yelizariev** [comment]
ok, you are right. There is a bug in 9.0 branch. Use 9.0-dev instead.
The same about 8.0 and 8.0-dev

**Comment by abhayvyas** [comment]
Can you please reopen this issue. I will try to resolve & make pull request when it solved.

**Comment by yelizariev** [comment]
You don't need to fix it. It have been fixed in 9.0-dev already
