### ISSUE TITLE
[9.0] [9.0-dev] Traceback on installation of saas_support module

### ISSUE THREAD

**Issue by abhayvyas** [it-projects-llc/odoo-saas-tools#129]
I get traceback when i am trying to install saas_support module. Please check following traceback
![saas support installation](https://cloud.githubusercontent.com/assets/16646042/12384492/8675962c-bdd8-11e5-9935-6e5d28e2ec42.png)

**Comment by yelizariev** [comment]
@iledarn

**Comment by yelizariev** [comment]
@abhayvyas we haven't updated this module for 9.0 version.

**Comment by yelizariev** [comment]
I don't know it will be fixed as I don't use it.
