### ISSUE TITLE
[8.0] Error in step 6

### ISSUE THREAD

**Issue by talazoft** [it-projects-llc/odoo-saas-tools#165]
Hi, I have got error when executing step 6, here is the error

> ConnectionError: HTTPConnectionPool(host='s1.mydomain.com', port=80): Max retries exceeded with url: /saas_server/new_database?access_token=IjOZGEFNs0EtM5lpE38wokyZ70h7sr&expires_in=3600&token_type=Bearer&state=%7B%22lang%22%3A+%22en_US%22%2C+%22tz%22%3A+false%2C+%22d%22%3A+%22t1.mydomain.com%22%2C+%22demo%22%3A+0%2C+%22is_template_db%22%3A+1%2C+%22addons%22%3A+%5B%5D%7D&redirect_uri=http%3A%2F%2Fs1.mydomain.com%3A80%2Fsaas_server%2Fnew_database&response_type=token&client_id=8681a668-cbe0-11e5-9cc4-001851ac713c&scope=userinfo+force_login+trial+skiptheuse (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

any help will be appreciated

**Comment by yelizariev** [comment]
There new short instruction https://github.com/yelizariev/odoo-saas-tools/tree/8.0
Try to use one instead
