### ISSUE TITLE
Migrate to the OCA repositories

### ISSUE THREAD

**Issue by coodec** [it-projects-llc/odoo-saas-tools#169]
Hi, my name is Daniel and I'm the OCA representative for Ecuador.

I'd like to invite you to join us and migrate your code to the OCA repos. Here you will gain exposure to your project and more important, you will get help from other OCA members and a wide comunity.

Would you like to join us?

Daniel.

**Comment by yelizariev** [comment]
Hi Daniel,
we don't move modules to OCA for different reasons. First of all we use GPL and LGPL licences. Second reason - OCA doesn't allow to get extra money for the modules (e.g. via publishing in app store). Third -  pull requests are often under review too much time

**Comment by coodec** [comment]
Hi, I do understand, there is no problem, I'd like to contribute to your work, as I think it's really useful for my company.

I'm working on V9, but I see that most of the work is done to V8.

Are you planning to migrate soon to V9 or do you plan to stay on V8 for a long time?.

I'd like to know to see if I help migrating to V9 or if I change my instance to V8 so I can work with the actual modules.

I have all my accounting modules (the important ones) in V9.

Please, tell me what do you need help for.

Daniel.

**Comment by yelizariev** [comment]
key saas modules are migrated to v9. Only few ones, which I don't use are still in v8 and probably are not inconsistent with some of new modules (e.g. saas_portal_signup and saas_pricing)

**Comment by coodec** [comment]
Hi, nice, I'll try to install them and test them as soon as possible.

Could you please tell me what do you need help for?.

Thanks a lot.

Daniel.

**Comment by yelizariev** [comment]
@coodec you can try to review sync_server part, which is real mess now. Some refactoring should be done there to make system more robust

**Comment by coodec** [comment]
Hi, I'll start reading and understanding the code of this module.

You have done a really nice job.

Daniel.
