### ISSUE TITLE
new branches

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#17]
Dear developers.
Thank you for your contribution.

I'd like to inform you, that now repo has 3 branches:
- 8.0 - default
- 9.0 - new branch, currently tested on https://github.com/odoo/odoo/tree/saas-6/ (rev. 2d581cd6654d53ede9bc8d4ee72d06d894756562)
- master - obsolete branch, that could be removed soon.

Regards,
Ivan

**Comment by saltonmassally** [comment]
Noted... thanks for the heads up

**Comment by yelizariev** [comment]
just deleted master branch
