### ISSUE TITLE
Better Exception Handling for saas_portal and saas_server

### ISSUE THREAD

**Issue by saltonmassally** [it-projects-llc/odoo-saas-tools#186]
At the moment exceptions raised by actions within saas_portal produces unhelpful error reporting with mostly "Internal Server Error" + unhelpful stack trace being shown and captured by logging.

Can we discuss how we can firstly:
- Ensure that proper message is sent to the UI
- Python logging captures the actual error raised on the server side

**Comment by yelizariev** [comment]
I guess #192 closes this issue
