### ISSUE TITLE
SaaS Server Sync

### ISSUE THREAD

**Issue by saltonmassally** [it-projects-llc/odoo-saas-tools#188]
@yelizariev in https://github.com/yelizariev/odoo-saas-tools/blob/8.0/saas_server/models/saas_server.py#L182 is there any particular reason why we are not filtering out deleted DBs?

**Comment by yelizariev** [comment]
because we don't know were they marked as deleted on portal

**Comment by yelizariev** [comment]
But I understand your concern. See also #169

**Comment by saltonmassally** [comment]
noted... thanks

**Comment by saltonmassally** [comment]
@yelizariev and @iledarn i plan on refactoring the "sync_server" routine do you have any thoughts you might want to see effected?
