### ISSUE TITLE
cannot create databases

### ISSUE THREAD

**Issue by gregory** [it-projects-llc/odoo-saas-tools#226]
<img width="647" alt="screenshot 2016-03-04 06 09 23" src="https://cloud.githubusercontent.com/assets/167488/13529269/26e3eec2-e1d0-11e5-9923-c10101a16aa7.png">

running from the latest 8.0 branch. 

when i tri to click send, i get the following: 
<img width="1222" alt="screenshot 2016-03-04 06 16 03" src="https://cloud.githubusercontent.com/assets/167488/13529361/9fce8d7e-e1d0-11e5-8699-e58e542248b0.png">

can't find anything from the logs

**Comment by yelizariev** [comment]
Database is created via Plan menu at Saas Portal database
