### ISSUE TITLE
error accessing the saas modules

### ISSUE THREAD

**Issue by GlauberF** [it-projects-llc/odoo-saas-tools#229]
after installed the modules in the same began to display the following error and does not access the templates, server.

![erro1](https://cloud.githubusercontent.com/assets/11314585/13634779/9c20a4aa-e5d6-11e5-88c6-98e8a27c8846.png)
![erro2](https://cloud.githubusercontent.com/assets/11314585/13634781/9d451be0-e5d6-11e5-9d34-af858a80bfe2.png)

**Comment by GlauberF** [comment]
![error](https://cloud.githubusercontent.com/assets/11314585/13635126/97474392-e5d8-11e5-9ddf-b14889848062.png)

**Comment by yelizariev** [comment]
Some foreign module payment_mercado... import library PoolLibrary, which is not available in your system.

**Comment by GlauberF** [comment]
but the module is not installed, it should not influence the application

**Comment by yelizariev** [comment]
It brokes system even if the module is not installed. Such imports must be done in try block
