### ISSUE TITLE
LGPL License on 8.0 Branch

### ISSUE THREAD

**Issue by nicholas-itpedia** [it-projects-llc/odoo-saas-tools#23]
First, thank you to all of the developer's working on this repository, especially Ivan Yelizariev. Very happy with the features and to see the active development. We will hopefully be able to add a developer / features in the future.

The license file listed in the 8.0 branch is LGPLv3. Odoo 8.0 is released under the AGPLv3 license. LGPLv3 is NOT compatible with AGPLv3.  The only license compatible with AGPLv3 is AGPLv3 and GPLv3 

For AGPLv3 and GPLv3 compatibility see:
https://en.wikipedia.org/wiki/Affero_General_Public_License
Section 13 of the AGPLv3 (http://www.gnu.org/licenses/agpl.html)

Highly recommend changing the 8.0 branch license to GPLv3 and keeping the 9.0 branch LGPLv3

**Comment by yelizariev** [comment]
Hi Nicholas,

thank you for your interesting in project.

I think your concerns about licensing makes sense. 
But I don't think that it's a important issue. As as understand, odoo don't care about using LGPL modules in 8.0. Also, they have specific interpretation for LGPL license: https://www.odoo.com/nl_NL/slides/slide/open-source-licenses-196

What do you think about using both license for 8.0 branch? Is it possible? If so, it could be helpfull if odoo change license for 8.0 to LGPL too.

**Comment by nicholas-itpedia** [comment]
Sorry for the delay in responding. I have been very busy.

I have previously seen and just now reviewed the link: https://www.odoo.com/nl_NL/slides/slide/open-source-licenses-196

No where in those slides does it mention being able to use LGPLv3 with AGPLv3 in **Odoo 8.0**. In Odoo v9.0, because the Community Edition will be re-licensed to LGPLv3, there is compatibility when AGPLv3 code (apps/module) depends/links to LGPLv3 code (app/module), like in slide 17. However, even in Odoo 9.0 LGPLv3 code cannot link to AGPLv3 code, similar to slide 15.

With Odoo 8.0, since the Odoo S.A. core modules are licensed with AGPLv3, the **ONLY** license a app/module can be is AGPLv3 AND GPLv3. This is due to the "viral" nature of the AGPLv3. GPLv3 code (apps/modules) that depend/link to AGPLv3 is compatible due to Section 13 of both:

AGPLv3  (http://www.gnu.org/licenses/agpl.html)
GPLv3 (http://www.gnu.org/licenses/gpl.html)

I agree that developing the software for these modules is very important, but so is the license selection. As the license is written now in the 8.0 branch, it is in violation of the AGPLv3 license of the rest of Odoo. Also, it looks like there might be some other license issues, example: 
1. https://github.com/yelizariev/odoo-saas-tools/blob/8.0/oauth_provider/validators.py
   - this has code based on FreeBSD license which is compatible, but the license is not properly documented in the source file  https://github.com/evonove/django-oauth-toolkit/blob/master/LICENSE
2. https://github.com/yelizariev/odoo-saas-tools/blob/8.0/saas_client/models/res_user.py  
   - AGPLv3 license compatible with Odoo 8.0 (AGPLv3) but there are issues in Odoo 9.0 in that it is not protected by the multi license compatibility in the LGPLv3 license.

I only found these 2 examples and have not done a complete search of the entire repository.

Selecting the correct license for the Odoo 9.0 branch is very important. If you choose LGPLv3, then proprietary (closed) code can be linked against any of the modules in the branch. If this is what you and the other developers want, then that is ok. Just be aware that anyone can link proprietary code.

If you choose GPLv3 or even AGPLv3  for Odoo 9.0 branch, then you enforce all of the copyleft requirements of those license (requirement to convey source changes, requirement to license additional code or linked code as GPLv3 or AGPLv3) and this code will stay free(libre) and open source.

Highly recommend changing the 8.0 branch license to GPLv3 and keeping the 9.0 branch LGPLv3

Also nearly all of the source files do not have any indication of the license written in the source file. I know it is easier to just rely on the LICENSE file in the root folder of the repository and there is controversy about including license in every source file, but then if and code is forked significantly, there can be questions over what license the code is released under. Also the Free Software Foundation recommends the license be placed in each source file (http://www.gnu.org/licenses/gpl-howto.html), as is the case with every source file that is in "Odoo Community".

If I have time, I will try to make commits and pull requests that fix some of these issues once you and the other developers decide on a license for each branch.

I will contact you in Skype or Google Hangouts to discuss this more in a voice call if you want.

**Comment by yelizariev** [comment]
Nicholas, thank you for review and your help about licensing.

I think we can change the 8.0 branch license to GPLv3 and keeping the 9.0 branch LGPLv3.

With regards LGPL vs AGPL for 9.0, I prefer LGPL because it allows more developers to be interested in the project.

@kaerdsar @dhbahr @jbustio 
what is your opinion about changing license?

**Comment by yelizariev** [comment]
@kaerdsar @dhbahr @jbustio

**Comment by dhbahr** [comment]
LGPLv3 sounds find to me for the 9.0 branch

**Comment by nicholas-itpedia** [comment]
@dhbahr thank you for your input. What do you want the 8.0 license to be?

@tarzan0820, @jbustio , @kaerdsar - please read this thread and respond indicating the license you want for 8.0 and 9.0

Once I receive a response from everyone, I will submit a pull request with updates to the license file in the root of the repository int he LICENSE file, as well as in the first lines of every source file, as recommended by the Free Software Foundation:

> Put all the copyright notices together, right near the top of each file.
> [How to use GNU licenses for your own software](http://www.gnu.org/licenses/gpl-howto.html)

Thank you all again for your work and effort on this project!

**Comment by kaerdsar** [comment]
@nicholas-itpedia I agree with the proposal and thanks for the help. We can have GPLv3 license for 8.0 branch and LGPLv3 license for 9.0 branch.

**Comment by nicholas-itpedia** [comment]
@kaerdsar Thank you for your input.

So far: 
@kaerdsar @yelizariev:
- agree on GPLv3 license for 8.0 branch and LGPLv3 license for 9.0 branch.

@dhbahr  
- agrees on LGPLv3 license for 9.0, but has not responded on the 8.0 license.

@tarzan0820 @jbustio 
- have not responded
- please read this entire issue and respond with your choice for a license

Thank you all for you input on this! 

I know for many developers, the license is not something they put much thought or effort into, but it is very important because it has significant impact on how your code is used in the future by others.

**Comment by dhbahr** [comment]
@nicholas-itpedia I'm fine with GPLv3 for 8.0

**Comment by saltonmassally** [comment]
@nicholas-itpedia  I agree with  GPLv3 license for 8.0 branch and LGPLv3 license for 9.0 branch.

**Comment by jbustio** [comment]
Sorry to delay in respond. I agree with GPLv3 license for 8.0 branch and LGPLv3 license for 9.0 branch

**Comment by nicholas-itpedia** [comment]
Thank you all for responding. I have started to update the license on the 8.0 branch. You can see an example at 

https://github.com/ITPS/odoo-saas-tools/commits/update_license

I would like to keep this issue open until I finish. I will try to finish tomorrow or by this weekend.

**Comment by njeudy** [comment]
As odoo V8.0 is not supported anymore, close this one

Feel free to reopen it if needed
