### ISSUE TITLE
Self service saas

### ISSUE THREAD

**Issue by dansalsero** [it-projects-llc/odoo-saas-tools#232]
Hi, I think that as databases and clients increase there is the need to create a way that the system generates a monthly invoice that the user can pay via the web page and automatically increases the database lifetime for one month.

So, if the client does not pay the invoice in the next period, the database will be blocked until the user register it's payment on the system.

This way the invoice/payment process may be automatic with no need of enterprise resources.

What do you think?

**Comment by yelizariev** [comment]
> So, if the client does not pay the invoice in the next period, the database will be blocked until the user register it's payment on the system.

already implemented.

>  system generates a monthly invoice that the user can pay via the web page and automatically increases the database lifetime for one month.

I think it could be done some way via built-in odoo features. But probably some updates is needed anyway

**Comment by bassn** [comment]
Hello,

> system generates a monthly invoice that the user can pay via the web page

this can be done in Odoo V8, if you activate Contract Management under Configuration / Configuration / Sales

Regards

Bassirou Ndaw
