### ISSUE TITLE
Close old issues so we can know how to help

### ISSUE THREAD

**Issue by dansalsero** [it-projects-llc/odoo-saas-tools#233]
Hi, I was looking at the issues to see on which may I help, but I found some really old issues and there is no clue about what may need help.

I'd like to contribute, but It would be helpful if the old unneeded issues are closed and new issues are open to plan the activities of new users.

Daniel.

**Comment by yelizariev** [comment]
Consider to take a look on issues with labels and skip ones without labels

**Comment by yelizariev** [comment]
also, you can suggest issues to close

**Comment by yelizariev** [comment]
I have added more labels for issues. It should help
