### ISSUE TITLE
limit number of user - ignore superadmin user

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#238]
https://github.com/yelizariev/odoo-saas-tools/blob/8.0/saas_client/models/res_user.py#L38

**Comment by ClaudiusChristian02** [comment]
Ok. could you explain the problem in english please. I understand there is a problem with the superadmin user. Isn't the super admin user someone like you or I? I thought each database had a user called an 'admin' user. If this is the case why are we ignoring the superadmin user? What is the role of the superadmin user?

**Comment by yelizariev** [comment]
Superadmin is a technical user. It doesn't belong to somebody and it is shared across SaaS Support Team to make customization 
Another user is Owner user, who can reference as "Admin", because he has more rights than his employees.

**Comment by yelizariev** [comment]
Done in #245 #244
