### ISSUE TITLE
mail servers

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#246]
Does somebody know any option to configure email servers automatically for every new saas client database?
We know pdd.yandex.ru. It's free, but its api doesn't cover all our needs (they probably will implement it in the future).

We have checked mailgun.com and amazon SES, but both of them don't allow receive emails.

cc @tarzan0820

**Comment by saltonmassally** [comment]
@yelizariev since sept. 2015 Amazon SES allows receiving email see http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email.html

I am yet to use this but use SES a lot for outbound emails. I am sure their API is flexible enough to suit you needs.

**Comment by yelizariev** [comment]
Yes, but as I understand it requires some coding from us to receive emails, because amazon doesn't provide imap\pop servers for receiving. Do I understand it correctly?

**Comment by saltonmassally** [comment]
Yes it will most likely require writing code as IMAP/POP is not offered. Apart from SES I don't really know other mailservers out there flexible enough

**Comment by yelizariev** [comment]
#258

**Comment by yelizariev** [comment]
mailgun is enough for now
