### ISSUE TITLE
Latest web_settings_dashboard dependency error in 8.0

### ISSUE THREAD

**Issue by cmsalmeida** [it-projects-llc/odoo-saas-tools#250]
The module web_settings_dashboard is only a 9.0.
This dependency breaks 8.0.

**Comment by yelizariev** [comment]
There is no web_settings_dashboard in dependency in 8.0 branch
https://github.com/yelizariev/odoo-saas-tools/blob/9.0/saas_client/__openerp__.py
https://github.com/yelizariev/odoo-saas-tools/blob/8.0/saas_client/__openerp__.py
