### ISSUE TITLE
local IP

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#259]
We need to add local_ip field to saas_portal.server in order to use it for sync_server method

**Comment by yelizariev** [comment]
also, local_port

**Comment by ClaudiusChristian02** [comment]
Ok. SO everyone should be used to these questions by now. 

1. How long will this issue take to complete?
1. What date will it be complete?

Another question I have is what problem does this issue fix? and who is working on fixing this issue?

**Comment by yelizariev** [comment]
It's done here https://github.com/yelizariev/odoo-saas-tools/pull/265 and we are about to deploy updates

The update speed up server-side requests

**Comment by yelizariev** [comment]
Done in https://github.com/yelizariev/odoo-saas-tools/pull/265 but not ported to 8.0

**Comment by yelizariev** [comment]
@iledarn
