### ISSUE TITLE
Amazon AWS

### ISSUE THREAD

**Issue by iledarn** [it-projects-llc/odoo-saas-tools#268]
We have created a new module named saas_sysadmin_aws https://github.com/iledarn/odoo-saas-tools/tree/9.0-saas_sysadmin_aws/saas_sysadmin_aws.
It is base module for setting credentials only and should be used in saas_sysadmin_route53.
@tarzan0820, please do refactor saas_sysadmin_route53

**Comment by yelizariev** [comment]
#267

**Comment by saltonmassally** [comment]
@iledarn noted

**Comment by iledarn** [comment]
@tarzan0820,
We also created saas_sysadmin_aws_route53 module that is based on your saas_sysadmin_route53.
I take the part about hosted zone creation and server settings and methods. But I don't need the A records creation on Plan and Clients. I'm about to use the new saas_sysadmin_aws_route53 with saas_sysadmin_mailgun module to create TXT and MX records on server's AWS Hosted Zone
