### ISSUE TITLE
Cron error

### ISSUE THREAD

**Issue by dansalsero** [it-projects-llc/odoo-saas-tools#293]
Hi, there is a cron error that keeps taking the postgres db down, the log is:

2016-05-29 07:19:41 CDT STATEMENT:  SELECT *
                                           FROM ir_cron
                                           WHERE numbercall != 0
                                              AND active
                                              AND nextcall <= (now() at time zone 'UTC')
                                              AND id=12
                                           FOR UPDATE NOWAIT

Which module do I have to check?.

Daniel.

**Comment by yelizariev** [comment]
I think, it's a built-in cron feature, isn't it.
What cron error do you mean?

**Comment by dansalsero** [comment]
When the saas tries to backup the databases, it adds too many connections to postgres and it ends up failing with a "too many clients" error.

I need to restart the server for it to go back online.

Daniel.

**Comment by njeudy** [comment]
it's a postgresql setup issue .. you have to upgrade postgresql conf I think.

feel free to create an other issue if you still have problem with it.
