### ISSUE TITLE
Unable to create Client DB from Template DB

### ISSUE THREAD

**Issue by fredmx** [it-projects-llc/odoo-saas-tools#311]
Hi, 

Would appreciate a great deal if you could lend a helping hand here... 

I am unable to create a client from the template DB created. It results in the following error. 
![screen shot 2016-06-21 at 11 55 56 am](https://cloud.githubusercontent.com/assets/20060286/16219784/61fab22a-37bb-11e6-886c-4132e402fe94.png)

Have I missed a step somewhere? 

I've followed the installation instructions from here (https://github.com/yelizariev/odoo-saas-tools/blob/9.0/docs/install.rst). Here is what I've **succeeded** so far: 
- setting up odoo.local (installed saas_portal only) and s1.odoo.local (installed saas_server). 
- able to create a template DB or plan (see screenshot below) with no issues so far. 
  ![image](https://cloud.githubusercontent.com/assets/20060286/16219749/1c444066-37bb-11e6-810f-bd0850bba41e.png)

Here are the screen shots to relevant settings: 
**/etc/hosts**
![image](https://cloud.githubusercontent.com/assets/20060286/16219855/bbdc7c10-37bb-11e6-8c5c-f16ab99295d8.png)

**/etc/nginx/sites-available/\* (linked from /etc/nginx/sites-enabled)**
![image](https://cloud.githubusercontent.com/assets/20060286/16219874/dfaf7854-37bb-11e6-89b1-22cb8dcb19eb.png)

**/etc/nginx/sites-available/s1.odoo.local (same for odoo.local, client-x.odoo.local)**
![image](https://cloud.githubusercontent.com/assets/20060286/16219916/0a9c2c92-37bc-11e6-9a23-5a1ae8f13aa6.png)

**Odoo Config File**
![image](https://cloud.githubusercontent.com/assets/20060286/16219938/2a054be0-37bc-11e6-938a-6be4381ce530.png)
(You can see I tried playing with the "dbfilter" option there. Both doesn't resolve the issue.)

**s1.odoo.local - Settings ==> Users ==> OAuthProviders -- SaaS**
![image](https://cloud.githubusercontent.com/assets/20060286/16219981/5fc747f6-37bc-11e6-9de3-26abde6a3dae.png)

**odoo.local - SaaS ==> SaaS ==> Servers ==> s1.odoo.local**
![image](https://cloud.githubusercontent.com/assets/20060286/16219991/85dcec84-37bc-11e6-8d2b-ac77501a2f8b.png)

**Comment by fredmx** [comment]
Here is the relevant log trace. 

![image](https://cloud.githubusercontent.com/assets/20060286/16220071/254e33f4-37bd-11e6-80f8-6d8d379d4627.png)

**Comment by yelizariev** [comment]
Thank you for detailed issue. 
I am about to fix it

**Comment by fredmx** [comment]
Hi Yelizariev, 

The fix works!!! Tested and verified. You are AWESOME!!
