### ISSUE TITLE
questions?

### ISSUE THREAD

**Issue by jacksolutions** [it-projects-llc/odoo-saas-tools#33]
please check attach screenshot
http://awesomescreenshot.com/06a593xw0c

i have created one template and running successfully,

what i have to select in that drop down to create other templates so that oauth works? whatever i am selecting in the dropdown it is applying that outh id to database uuid and conflicting in duplicate UUID?

what am i doing wrong? even in your instructions you have not listing anything about that dropdown?

**Comment by saltonmassally** [comment]
Jack we generally do not use that form to create template database... instead we use the "create or edit" feature of the many2one field... so type the name of the template db e.g. 't1.odoo.local' and once you see the "create t1.odoo.local" option appear click it.

Hope this helps

**Comment by jacksolutions** [comment]
oh yes thank you, that worked!

On Sat, Sep 19, 2015 at 5:06 PM, Salton Massally notifications@github.com
wrote:

> Jack we generally do not use that form to create template database...
> instead we use the "create or edit" feature of the many2one field... so
> type the name of the template db e.g. 't1.odoo.local' and once you see the
> "create t1.odoo.local" option appear click it.
> 
> Hope this helps
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yelizariev/odoo-saas-tools/issues/33#issuecomment-141653580
> .

## 

Cheers,

Jaykishan Vansadawala
(Jack Solutions)
Mob:- +91-9879455635

**Comment by saltonmassally** [comment]
You are welcome; please close this issue if that is all

**Comment by jacksolutions** [comment]
yes it is thank you
