### ISSUE TITLE
Popup blocked:

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#330]
We have fix the issue with popup when clicking "Log in" on saas_portal.client  form
I think `widget="url"` should help

**Comment by erkesado** [comment]
Dear yelizariev,

How to configure SaaS server on a different server than Portal server?
I have one Portal server and one domain which is mydomain.com. Can I have two SaaS servers? First SaaS server is located in datacenter A. Second SaaS server is located in datacenter B. 
- User1 goes to mydomain.com and creates user1.mydomain.com database on first SaaS server.
- User2 goes to mydomain.com and creates user2.mydomain.com database on second SaaS server.
  I understand that this scenario is feasible with Odoo SaaS Tools. Is that true?

**Comment by yelizariev** [comment]
I am about to fix this issue. 
@ilmir-k @iledarn please review the solution
![screenshot-saas-portal-8 local 2016-11-14 20-41-09](https://cloud.githubusercontent.com/assets/186131/20270929/d33c2876-aaaa-11e6-8047-d381053a537d.png)

**Comment by yelizariev** [comment]
@erkesado I am sorry for ignoring your question. Consider to create a separate issue next time... 
Short answer for you: use this module https://github.com/it-projects-llc/odoo-saas-tools/tree/10.0/saas_sysadmin_route53

**Comment by yelizariev** [comment]
https://github.com/it-projects-llc/odoo-saas-tools/pull/388
