### ISSUE TITLE
Forbid creating from Clients menu

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#332]
There is still a way to create saas_portal.client from Clients menu:
![1470633554328screensave](https://cloud.githubusercontent.com/assets/186131/17469962/bdd58280-5d51-11e6-8f62-6ebcd63590be.png)

This has to be forbidden. Probably, we have to add a warning message by redefining default_get or something like that. It can be done by checking context - if it has context from Clients menu, then raise warning

**Comment by njeudy** [comment]
Think is is ok now. close this one too

![image](https://user-images.githubusercontent.com/995787/36945567-c69bcc1c-1fb0-11e8-86a1-607f55278f84.png)
