### ISSUE TITLE
update dependencies info for website_sale_require_login

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#342]
After accepting this PR https://github.com/OCA/e-commerce/pull/124
The [note](https://github.com/it-projects-llc/odoo-saas-tools/blob/9.0/docs/dependencies.rst#website_sale_require_login) about website_sale_require_login has to be updated

**Comment by ovnicraft** [comment]
So there're plans to migrate to 10.0 ?

**Comment by yelizariev** [comment]
I close this issue as the note is updated

**Comment by yelizariev** [comment]
@ovnicraft I don't have such plans yet. There is chance, that the module works in 10.0 without any updates
