### ISSUE TITLE
Error in saas_client when creating a template DB

### ISSUE THREAD

**Issue by ricardosousa1** [it-projects-llc/odoo-saas-tools#358]
Hello,
First things first congratulations for your project.

**My Issue:**

Im always getting the error below when I try to "Create Template DB", in spite of checking "Install Demo Data", choosing "TimeZone" or not...

**The Error:**

![selection_016](https://cloud.githubusercontent.com/assets/23120374/19805872/e7547d8a-9d0e-11e6-99eb-fb030b0cdabb.png)

What am I doing wrong? Thanks in advance!

**Comment by yelizariev** [comment]
Which version do you use?

**Comment by ricardosousa1** [comment]
Hello @yelizariev thanks for the reply. Do you mean which odoo version Im using? Im using version 9.0

**Comment by ricardosousa1** [comment]
Problem solved. I dont know if this is the right solution but i opened /openerp/addons/saas_client/data/**ir_cron.xml** and did the following changes:

`
<?xml version="1.0" encoding="UTF-8"?>
<openerp>
    <data>
        <record id="mail.ir_cron_module_update_notification" model="ir.cron">
            <field name="name">XXXXXX</field>
            <field name="interval_type">days</field>
            <field name="numbercall">-1</field>
            <field name="nextcall" eval="(DateTime.now() + timedelta(hours=12)).strftime('%Y-%m-%d %H:%M:%S')" />
        </record>
    </data>
</openerp>
`

...Followed by the rest of the installation steps. Now the project is running without issues. Thank you.

**Comment by yelizariev** [comment]
@ricardosousa1 Could make a pull request with the fix?

**Comment by njeudy** [comment]
We didi not encounter this bug anymore think it is resolved.

feel free to open new issue if you encounter this.
