### ISSUE TITLE
saas_portal_signup : DB creation compulsory 

### ISSUE THREAD

**Issue by ygol** [it-projects-llc/odoo-saas-tools#374]
Is it so that the module force a new user to create a database?

use case: A user select a product from the shop and in the checkout he click on "Sign up and checkout" but now he arrives to the form where he must create a database
![image](https://cloud.githubusercontent.com/assets/2945174/20037902/96f794fa-a432-11e6-97d7-70ecb783677d.png)

**Comment by iledarn** [comment]
@ygol ,
this is done in the saas_portal_start module.
You can uninstall it to have ordinary form
