### ISSUE TITLE
how to upgrade plan

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#383]
Hello i try to find out the way to upgrade the package when the client want to upgrade but no where plz help. how can i do that?

**Comment by yelizariev** [comment]
Please clarify what do you mean. What is "upgrading of the package?"

**Comment by dansalsero** [comment]
I think he means the way to plan an upgrade, for example...
should all databases migrate a the same time?
it's possible to migrate client databases without migrating the saas portal and servers?
it's better to migrate the portal and server before client databases?

how we should upgrade from 9 to 10, considering the need to migrate portal, server and client databases....

**Comment by 360org** [comment]
@dansalsero another idea :)
but me mean if i set 2 package 1 for standard & 1 for enterprise if client want to upgrade from standard to enterprise how could i do that?

**Comment by coodec** [comment]
I'd like to know how to do that to. :D

**Comment by yelizariev** [comment]
Currently, it's not possible to change saas plan for existed saas client. 
What could you do to increase\decrease available features for uses is either install\unistall modules that provide that features or grant\remove access to enterprise features via `res.groups`

**Comment by yelizariev** [comment]
@dansalsero as for upgrading from 9 to 10 for example, it's a huge task and saas will not cover it. You need to migrate a database manually with [OpenUpgrade](https://github.com/OCA/OpenUpgrade) tool. What saas has to do is provide a possibility to register database from dump.

**Comment by ygol** [comment]
@yelizariev so is it currently possible to register (add to saas) a manually created database (dump restore or dbcreate)?

**Comment by yelizariev** [comment]
@ygol I think it's possible. Theoretically, you can do it by creating new client, replacing created db with the dump and update database.uuid  in ir.config_parameter. Obviously, it's not quite convenient and the feature has to be added.

**Comment by njeudy** [comment]
Think we can close this issue, In fact upgrade odoo need some extra like openupgrade.

We need to try  to find a solution maybe but for now, you have to manually upgrade your database.

@yelizariev it can be a roadmap or a wishlist somewhere to log this feature request ?
