### ISSUE TITLE
[v10] website_sale_require_login 

### ISSUE THREAD

**Issue by zimbora69** [it-projects-llc/odoo-saas-tools#398]
Hello,

First of all let me congratulate you for this great project.

Second of all, when installing **saas_portal_sale_online**, that module has a dependency website_sale_require_login  that isn't migrated on **OCA/e-commerce.git#10.0**. What should I do?

**Comment by zimbora69** [comment]
PR https://github.com/OCA/e-commerce/pull/138

**Comment by 360org** [comment]
clone https://github.com/it-projects-llc/e-commerce/tree/10.0-website_sale_require_login
this one will be fixed

**Comment by zimbora69** [comment]
thanks! @W360S
