### ISSUE TITLE
[v10] Installing saas_portal_sale

### ISSUE THREAD

**Issue by zimbora69** [it-projects-llc/odoo-saas-tools#401]
ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq" DETALHE: Key (key)=(saas_portal.page_for_nonfree_subdomains) already exists. " while parsing /opt/odoo/odoo100/addons/odoo-saas-tools/saas_portal_sale/data/ir_config_parameter.xml:4, near <record id="saas_page_for_nonfree_subdomains" model="ir.config_parameter"> <field name="key">saas_portal.page_for_nonfree_subdomains</field> <field name="value">/</field> </record>

**Comment by yelizariev** [comment]
@zimbora69 
remove `saas_portal.page_for_nonfree_subdomains` key from Settings / System Parameters

@iledarn 
possible solution is using yml file with try block instead of xml

**Comment by alexanderradahl** [comment]
This solved the issue for me!
