### ISSUE TITLE
How to hidden saas portal from the customer?

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#402]
Hello i'm success install saas portal but when create customer they still see the saas portal & OAuth Applications, Database UUID
ho can i hide from them? plz see the attach files
![2016-11-19_11-47-25](https://cloud.githubusercontent.com/assets/8590556/20453130/447389d4-ae4e-11e6-817b-30e18ba4df99.png)
![2016-11-19_11-47-03](https://cloud.githubusercontent.com/assets/8590556/20453139/4e13d1ce-ae4e-11e6-8e53-cfbb9c8bd846.png)

**Comment by yelizariev** [comment]
@W360S will you able to create a PR with the fix?

**Comment by 360org** [comment]
What does it mean PR @yelizariev  if any thing i can help ?

**Comment by yelizariev** [comment]
Pull Request. Are you odoo developer?

**Comment by 360org** [comment]
How to create pull request? normally i just apt-get update & apt-get upgrade odoo will update the lasted version of odoo but with saas how can i create pull request?

**Comment by 360org** [comment]
is it work if i rm the old one then clone the new one?

**Comment by yelizariev** [comment]
I asked you you to fix the source and send updates to us =)

**Comment by 360org** [comment]
sorry im not odoo dev just start work with odoo

**Comment by 360org** [comment]
but if you can guide me i may fixed this :)

**Comment by yelizariev** [comment]
@W360S you can find information about access and module development here: https://odoo-development.readthedocs.io/en/latest/dev/access/index.html

**Comment by yelizariev** [comment]
fixed in 10.0
