### ISSUE TITLE
V9-Can't access any of saas.py created databases.

### ISSUE THREAD

**Issue by ronozoro** [it-projects-llc/odoo-saas-tools#404]
Hi there

i have a very strange problem here ,  i can't access any of the  databases which created by saas.py script.Firstly i added the modules in a VM and run the saas.py and it told me that saas is ready.i follow your guide to configure odoo and nginx and i think i did well in that, the problem here that when i try to access http://server-1.saas-portal-9.local or http://saas-portal-9.local it tells me that server not found , i tried ping server-1.saas-portal-9.local and ping saas-portal-9.local and it's succeeded on my vm but not on my pc but when i try to ping with http:// before the url , actually i didn't get any response either on vm or PC .when i try to type my the machine ip in my pc which is (192.168.197.129) actually it opens the odoo web create database page , i know i don't see another databases because of the filter,so why is that happen?.
Could any body help me ?

**Comment by yelizariev** [comment]
Do you have corresponded records in ``/etc/hosts`` ?

    sudo bash -c "python saas.py --print-local-hosts >> /etc/hosts"

**Comment by ronozoro** [comment]
@yelizariev actually yes , here is a screenshot of my hosts file ,also I'm running Ubuntu 16.04

![screen shot 2016-11-22 at 8 10 33 pm](https://cloud.githubusercontent.com/assets/11825933/20535982/e0bd719e-b0ef-11e6-830d-68b294d9a480.png)

**Comment by yelizariev** [comment]
As I understand, you are trying to access to saas through your PC, while saas is installed on ubuntu.
In that case, you need to add similar records to window hosts file with ip address of your ubuntu system (192.168.197.129)
