### ISSUE TITLE
how to redirect from http://example.com to http://www.example.com

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#410]
Hello could you plz help
i need to config Nginx to default to www.domain.com is there anyway to to that?
the current config work fine for http://domain.com but i need work with www.domain.com

**Comment by yelizariev** [comment]
It's quite common issue. Try to google "redirect to www nginx".

From saas point of view domain name with www has to be agreed with --db-filter and database name
