### ISSUE TITLE
The "Create client" window remains opened after the client database had been successfully created

### ISSUE THREAD

**Issue by infoelliex** [it-projects-llc/odoo-saas-tools#42]
The "Create client" window remains opened after the client database had been successfully created (see img below).

![image](https://cloud.githubusercontent.com/assets/14144782/10171824/0815b760-66aa-11e5-82da-a2c469af299f.png)

I can just manually close the pop up window. But the thing is that if I click the "Create" button again by mistake, a 500 error will show on the screen.

**Comment by infoelliex** [comment]
The "Create client" window remains opened after the client database had been successfully created (see img below).

![image](https://cloud.githubusercontent.com/assets/14144782/10171824/0815b760-66aa-11e5-82da-a2c469af299f.png)

I can just manually close the pop up window. But the thing is that if I click the "Create" button again by mistake, a 500 error will show on the screen.

**Comment by askz** [comment]
The same here, and when the popup opens, I have an OAuth error with token id.

**Comment by yelizariev** [comment]
fixed
