### ISSUE TITLE
Error when running automated script

### ISSUE THREAD

**Issue by augustosamame** [it-projects-llc/odoo-saas-tools#435]
Hi. When running the automated script:

sudo python saas.py --portal-create --server-create --plan-create --run --odoo-script=/opt/odoo/odoo-10.0/odoo-bin --odoo-config=/etc/odoo.conf

I get the following error

2016-12-22 16:39:00
saas.py >>> RPC Execute, auth.oauth.provider, read, [False], {}
Traceback (most recent call last):
  File "saas.py", line 183, in main
    rpc_init_server(args.get('server_db_name'))
  File "saas.py", line 300, in rpc_init_server
    oauth_provider = rpc_xmlid_to_object(auth, 'saas_server.saas_oauth_provider', 'auth.oauth.provider')
  File "saas.py", line 331, in rpc_xmlid_to_object
    read = rpc_execute_kw(auth, model, 'read', [res_id])
  File "saas.py", line 269, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'None'>

On this issue:

https://github.com/it-projects-llc/odoo-saas-tools/issues/337

someone had a similar error and solved it by installing this module:

website_sale_require_login

I have installed the module as well from here (only one I could find for version 10):

https://github.com/iledarn/e-commerce/tree/10.0-mig-website_sale_require_login

But still get the same error.

I am running Odoo Community version 10

Any help is appreciated

**Comment by 360org** [comment]
remove the version that you have install and try this 
https://github.com/it-projects-llc/e-commerce/tree/10.0-website_sale_require_login
remember you have to clone exactly the version  10.0-website_sale_require_login not 10.0
i believe error will fixed

**Comment by augustosamame** [comment]
I removed the module and installed the one you indicated. After instance reboot I tried the script again but I'm getting the same error:

2016-12-22 17:09:48
saas.py >>> RPC Execute, ir.model.data, xmlid_to_res_id, ['saas_server.saas_oauth_provider'], {}

2016-12-22 17:09:48
saas.py >>> auth, ('server-1.saas-portal-10.local', <ServerProxy for localhost:8069/xmlrpc/2/object>, 1, 'admin')

2016-12-22 17:09:48
saas.py >>> RPC Execute, auth.oauth.provider, read, [False], {}
Traceback (most recent call last):
  File "saas.py", line 183, in main
    rpc_init_server(args.get('server_db_name'))
  File "saas.py", line 300, in rpc_init_server
    oauth_provider = rpc_xmlid_to_object(auth, 'saas_server.saas_oauth_provider', 'auth.oauth.provider')
  File "saas.py", line 331, in rpc_xmlid_to_object
    read = rpc_execute_kw(auth, model, 'read', [res_id])
  File "saas.py", line 269, in rpc_execute_kw
    model, method, rpc_args, rpc_kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
Fault: <Fault 2: 'None'>

**Comment by 360org** [comment]
try to run manual way https://github.com/it-projects-llc/odoo-saas-tools/blob/10.0/docs/install.rst

**Comment by 360org** [comment]
i know your problems :) just remove your saas tools then clone with v10 https://github.com/it-projects-llc/odoo-saas-tools/tree/10.0 it will work

**Comment by augustosamame** [comment]
thanks. ill try right away because manual install was not going well either

i got stuck at this step:

Configure Server Database * Activate the developer mode via "(?)/About"
menu at the top right-hand corner * Open Settings/Users/OAuth Providers -
SaaS

there was no oauth providers option in settings user even with all saas
modules installed in addons, rebooting the server and developer mode active

will check and report back



2016-12-22 13:25 GMT-05:00 W360S CORP <notifications@github.com>:

**Comment by augustosamame** [comment]
Hi. I just realized that's the exact repository I'm using. I give up.

I have setup an Upwork job if anyone is interested in doing this for a fee:

https://www.upwork.com/jobs/~0122a26968897343dc



2016-12-22 13:30 GMT-05:00 Augusto Samame <augustosamame@gmail.com>:

**Comment by 360org** [comment]
and try with this link it contain website_sale_require_login https://github.com/it-projects-llc/e-commerce/tree/10.0 
i just did and it work.

**Comment by 360org** [comment]
ok try me :) i'll do it for you :) https://www.fiverr.com/w360scorp/setup-odoo-10-with-saas-for-you-to-provide-odoo-service-to-client
just give me your vps info.

**Comment by yelizariev** [comment]
@augustosamame The log you provided doesn't contain essential info. Try to send more logs, especially lines before the error

**Comment by 360org** [comment]
this one had fixed.
