### ISSUE TITLE
error install odoo-saas-tools via docker

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#439]
Hello i have problems when i install saas via docker allthing work fine the only error connecting to the server. plz help.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 866, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 854, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<string>", line 2, in action_sync_server
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 361, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/mnt/extra-addons/odoo-saas-tools/saas_portal/models/saas_portal.py", line 130, in action_sync_server
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: NOT FOUND 
 Message: 
    
    <!DOCTYPE html>
        <html lang="en-US" data-oe-company-name="My Company">
            <head>
                <meta charset="utf-8"/>
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>

                <title>404 | My Website</title>
                <link type="image/x-icon" rel="shortcut icon" href="/web/image/website/1/favicon/"/>

                <script type="text/javascript">
                    var odoo = {
                        csrf_token: "79b04fce99079a30b25f96ee21eb9fe22f6dc0c7o",
                    };
                </script>

                
            <meta name="description"/>
            <meta name="keywords"/>
            <meta name="generator" content="Odoo"/>

            <meta property="og:title" content="404"/>
            <meta property="og:site_name" content="My Company"/>
            

            
            

            <script type="text/javascript">
                odoo.session_info = {
                    is_superuser: false,
                    is_frontend: true,
                };
            </script>

            
            <link href="/web/content/246-bd08794/web.assets_common.0.css" rel="stylesheet"/>
            
            <link href="/web/content/320-4f300fb/web.assets_frontend.0.css" rel="stylesheet"/>
            <link href="/web/content/321-4f300fb/web.assets_frontend.1.css" rel="stylesheet"/>
            
            
            

            
            <script  type="text/javascript" src="/web/content/251-bd08794/web.assets_common.js"></script>
            
            <script  type="text/javascript" src="/web/content/323-4f300fb/web.assets_frontend.js"></script>
            
            
            
        
            </head>
            <body>
                
        
        
        
            
                
            
            
                
            
        
        
        
        

        
        <div id="wrapwrap" class="">
            <header>
                <div class="navbar navbar-default navbar-static-top">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-top-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a href="/" class="navbar-brand logo">
            <img src="/logo.png" alt="Logo of My Company" title="My Company"/>
        </a>
    </div>
                        <div class="collapse navbar-collapse navbar-top-collapse">
                            <ul class="nav navbar-nav navbar-right" id="top_menu">
                                
                                    
    <li>
        <a href="/">
            <span>Home</span>
        </a>
    </li>
    

                                
                                    
    <li>
        <a href="/page/contactus">
            <span>Contact us</span>
        </a>
    </li>
    

                                
                                
                                
                            <li class="divider"></li>
        <li>
            <a href="/web/login">
                <b>Sign in</b>
            </a>
        </li>
    </ul>
                        </div>
                    </div>
                </div>
            </header>
            <main>
                
        <div id="wrap">
            
            <div class="oe_structure oe_empty">
                <div class="container">
                    <h1 class="mt32">404: Page not found!</h1>
                    <p>
                        The page you were looking for could not be found; it is possible you have
                        typed the address incorrectly, but it has most probably been removed due
                        to the recent website reorganisation.
                    </p>
                    <p>Maybe you were looking for one of these popular pages ?</p>
                    <ul>
                        <li><a href="/">Homepage</a></li>
                        <li><a href="/page/website.contactus/">Contact Us</a></li>
                    </ul>
                </div>
            </div>

            
        </div>
    
            </main>
            <footer>
                <div id="footer" class="container hidden-print">
      <div class="row">
        <div class="col-md-4 col-lg-3">
          <h4>Our Products &amp; Services</h4>
          <ul class="list-unstyled" id="products">
            <li>
              <a href="/">Home</a>
            </li>
          </ul>
        </div>
        <div class="col-md-4  col-lg-3" id="info">
          <h4>Connect with us</h4>
          <ul class="list-unstyled">
            <li>
              <a href="/page/website.contactus">Contact us</a>
            </li>
          </ul>
          <ul class="list-unstyled">
            <li>
              <i class="fa fa-phone"></i>
              
            </li>
            <li>
              <i class="fa fa-envelope"></i>
              <span>info@yourcompany.com</span>
            </li>
          </ul>
          <h2>
            
            
            
            
            
            
          </h2>
        </div>
        <div class="col-md-4 col-lg-5 col-lg-offset-1">
          <h4>
            <span>My Company</span>
            <small> - <a href="/page/website.aboutus">About us</a></small>
          </h4>
          <div>
            <p>
                            We are a team of passionate people whose goal is to improve everyone's
                            life through disruptive products. We build great products to solve your
                            business problems.
                        </p>
            <p>
                            Our products are designed for small to medium size companies willing to optimize
                            their performance.
                        </p>
          </div>
          
    

        </div>
      </div>
    </div>
  <div class="container mt16 mb8">
            <div class="pull-right">
                Create a <a href="http://www.odoo.com/page/website-builder">free website</a> with
                <a class="label label-danger" href="http://www.odoo.com/page/website-builder">Odoo</a>
            </div>
            <div class="pull-left text-muted" itemscope="itemscope" itemtype="http://schema.org/Organization">
                Copyright &copy; <span itemprop="name">My Company</span>
            </div>
        </div>
    </footer>
        </div>
        
        
    
            </body>
        </html>

**Comment by yelizariev** [comment]
Do you use https://github.com/it-projects-llc/install-odoo ?

**Comment by 360org** [comment]
yeap i try to install with https://github.com/it-projects-llc/install-odoo
then run update install vim in container

**Comment by yelizariev** [comment]
What is your db-filter?
https://it-projects-llc.github.io/odoo-saas-tools/blog/reason-not-found
