### ISSUE TITLE
Bug on template creation

### ISSUE THREAD

**Issue by askz** [it-projects-llc/odoo-saas-tools#44]
Hi, first of all, thanks for your awesome work, I just discovered this 1 week ago and I'm testing for the first time today. 

I have problems when my first template is created, when I click log in, there isn't any modules that shows in menu :
![screen shot 2015-10-02 at 18 43 04](https://cloud.githubusercontent.com/assets/854038/10252079/77080032-6935-11e5-8c09-fcc23c2544f6.png)

and when i force the settings menu with local modules to open and try to install one, Odoo says that I haven't the rights to do this : 

![screen shot 2015-10-02 at 18 45 05](https://cloud.githubusercontent.com/assets/854038/10252138/cfb1b4e4-6935-11e5-8739-000dc45512fa.png)

am I doing anything wrong? 

Best regards

**Comment by yelizariev** [comment]
Hi, it seems, that this bug is already fixed: https://github.com/kaerdsar/odoo-saas-tools/commit/1be2e758da3c4f81cf148190653a67c615c5bebb
Try to update source and repeat usage instruction

**Comment by askz** [comment]
Hi thanks for your fast reply, it worked, mea culpa to don't have the last sources. :)
