### ISSUE TITLE
[v10] Registration via web portal gives 403 - Unauthorized

### ISSUE THREAD

**Issue by augustosamame** [it-projects-llc/odoo-saas-tools#452]
When registering through the web portal in a SaaS standard v10 install, a 403 screen is shown as soon as you press the Register button.

We have traced the issue to the saas_portal_signup module. In the controllers/main.py line 24 it tries to access to the saas_portal.plan model but public user has no privileges to it.

Adding employee privileges to the public user serves as a workaround but it's certainly not ideal.

**Comment by augustosamame** [comment]
Ok, solved this by adding Read Privileges to the Public user for saas_portal.plan model. I would submit a PR if I knew Python well enough.

**Comment by ovnicraft** [comment]
@augustosamame So you can explain the steps to solved and we can help you to make a PR.

**Comment by augustosamame** [comment]
I guess what the PR would have to do is to have the module add Read privileges to the Public user to saas_portal.plan model
It is what i did using the Technical - Database Structure - Models menu option.

![image](https://cloud.githubusercontent.com/assets/16038063/22907964/d6c290aa-f219-11e6-8db2-bc7013932e7c.png)

**Comment by iledarn** [comment]
fixed in https://github.com/it-projects-llc/odoo-saas-tools/pull/534
