### ISSUE TITLE
SaaS Pricing cannot install

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#453]
Hello!
i can see SaaS Pricing module but unable to install
did i wrong somethings?
![2017-01-30_18-25-03](https://cloud.githubusercontent.com/assets/8590556/22421398/821503ea-e719-11e6-9281-5e31b7f177e1.png)

**Comment by repodevs** [comment]
@W360S I think it's replaced using `product_price_factor*` module, is it correct @yelizariev ?

**Comment by yelizariev** [comment]
SaaS Pricing is neither finished nor maintained. I don't know much about this module. Take a look on its code
