### ISSUE TITLE
Can't access with /web/signup 403 Forbidden error

### ISSUE THREAD

**Issue by zimbora69** [it-projects-llc/odoo-saas-tools#455]
Template user for new users created through signup is 'xpto', this user has has public and portal permissions. What permission am I missing?

**Log of error when trying to access /web/signup with anonymous tab**

403: Forbidden
The page you were looking for could not be authorized.

**Comment by repodevs** [comment]
@zimbora69 which odoo version you use ?

**Comment by augustosamame** [comment]
Maybe this is the same issue? https://github.com/it-projects-llc/odoo-saas-tools/issues/452

**Comment by zimbora69** [comment]
@augustosamame It's exactly that, thanks! Needs a PR, if I have the time I'll do that.

@repodevs v10

**Comment by zimbora69** [comment]
I'll close this on and leave yours opened.
