### ISSUE TITLE
Error when creating templatedb

### ISSUE THREAD

**Issue by arnelap** [it-projects-llc/odoo-saas-tools#468]
At step 6, Create plan, when i click Create Template DB i get the error:

You try to install module 'saas_client' that depends on module 'access_limit_records_number'...
access_limit_records_number is a paid module, you need to buy it for this to work?

If i try to push the create template db button again i get:
 Message: duplicate key value violates unique constraint "saas_server_client_client_id_uniq"
DETAIL:  Key (client_id)=(.....) already exists.

**Comment by 360org** [comment]
Delet the db template & create new one it will fixed.

**Comment by arnelap** [comment]
actually i solved it by manually removing the dependency from the saas_client add-on __openerp.py
not sure if stuff will work as it should...

**Comment by arnelap** [comment]
nope, now when i create a client:

  File "/usr/lib/python2.7/dist-packages/odoo/addons/saas_portal/wizard/config_wizard.py", line 86, in do_upgrade_database
    raise Warning('Reason: %s \n Message: %s' % (res.reason, res.content))
Warning: Reason: INTERNAL SERVER ERROR 
 Message: 'base.limit.records_number'


I suppose that is bcz of the missing dependency?

**Comment by repodevs** [comment]
@arnelap have you read the dependencies ? https://github.com/it-projects-llc/odoo-saas-tools/blob/10.0/docs/dependencies.rst
you must add `access_limit_records_number` to your addons before installing `saas_client`
