### ISSUE TITLE
error when create new template (plan)

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#476]
Hello i need help anyone have same issues like that plz help.
WARNING mydomain.com.vn odoo.models: saas_portal.database.write() with unknown fields: db_storage, file_storage, max_users, total_storage_limit, users_len in the log file and
The plan has been sync but it not success.

when i try to resarch on google i see that same issues here. http://05517-124-f4719e-base.runbot.it-projects.info/runbot/build/2978

**Comment by yelizariev** [comment]
It's not a error, but warning. It's not the reason of syncing issue
