### ISSUE TITLE
[10.0] create template db without saas.py

### ISSUE THREAD

**Issue by ovnicraft** [it-projects-llc/odoo-saas-tools#490]
Hi, i am testing modules so  i want to know what steps to follow to create a template db for a plan.

I my guess:
1. Create a db as usual in odoo, install modules.
2. Configure in SaaS db temaplate.

UUID for db is not editable.

**Comment by FLwalkaway** [comment]
you should add your template db name in /etc/hosts

**Comment by ovnicraft** [comment]
@FLwalkaway thats to resolve, so my question goes in favor to know from backend how the admin configure saas server.
