### ISSUE TITLE
Need help with odoo database format

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#491]
Hello i need help odoo doesn't allow me to create db with domain name what can i do now?
![2017-04-21 00-59-30 odoo](https://cloud.githubusercontent.com/assets/8590556/25245228/f1f11e8a-262d-11e7-946d-e6d0d13d77a8.png)

**Comment by iledarn** [comment]
@W360S ,
It is due for https://github.com/odoo/odoo/pull/16501

We still can create databases with dots in names from command line:

::

 ./odoo-bin -d w360s.com

**Comment by iledarn** [comment]
@W360S ,
It is due for odoo/odoo#16501

We still can create databases with dots in names from command line:
i.e.
./odoo-bin -d w360s.com

**Comment by 360org** [comment]
thanks for your help, i dont know what happen, but i have deleted server and install again and it work 👍
