### ISSUE TITLE
access rights on saas Client

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#51]
I've developed set of modules on access rights (modules are not ported to 8.0 yet):

https://github.com/yelizariev/addons-yelizariev/tree/9.0/ir_rule_protected
- makes impossible for non-superuser admin edit\delete protected ir.rule

https://github.com/yelizariev/addons-yelizariev/tree/9.0/access_restricted
- The module makes impossible for administrator set (and see) more access rights (groups) than he already have. _(follow the link for more description)_

https://github.com/yelizariev/addons-yelizariev/tree/9.0/hidden_admin
- makes admin invisible

I suggest to add **ir_rule_protected** and **access_restricted** to **saas_client**'s dependencies and delete this rule: https://github.com/yelizariev/odoo-saas-tools/blob/f5174ed5102ef374ccef22b1acfcd9382fca505f/saas_client/security/rules.xml#L5-L11

I prefer to add **hidden_admin** too, but this is discussable.

**Comment by yelizariev** [comment]
Other modules to discuss:
https://github.com/yelizariev/addons-yelizariev/tree/9.0/access_apps
https://github.com/yelizariev/addons-yelizariev/tree/9.0/access_settings_menu

**Comment by yelizariev** [comment]
Probably all listed above modules can be optional and installed by SaaS provider if needed.

**Comment by yelizariev** [comment]
So, possible solution here is remove security rules from /saas_client/security/rules.xml files and add note about usefull modules to saas_client/README.rst

**Comment by saltonmassally** [comment]
@yelizariev your reasoning makes sense however I have the following questions:

1) If hidden_admin and access_restricted are installed won't these rules conflict? https://github.com/yelizariev/addons-yelizariev/blob/9.0/access_restricted/security.xml#L4 or https://github.com/yelizariev/addons-yelizariev/blob/9.0/hidden_admin/security.xml#L4 
I didn't really test it but which will be used?

**Comment by saltonmassally** [comment]
:+1:  for removing  security rules from /saas_client/security/rules.xml however regardless of how useful the three modules are, ir_rule_protected, access_restricted, and hidden_admin, are they really dependencies needed for saas_client to work? As much as in my use case these are absolutely a must I think they should be installed by developer he he/she chooses.

However I suggest we reference these in the readme of saas_portal... your first comment on this issue will make a nice description to start with

**Comment by saltonmassally** [comment]
My above comment also applies to 
https://github.com/yelizariev/addons-yelizariev/tree/9.0/access_apps
https://github.com/yelizariev/addons-yelizariev/tree/9.0/access_settings_menu

**Comment by yelizariev** [comment]
https://github.com/yelizariev/addons-yelizariev/blob/9.0/access_restricted/security.xml#L4 or https://github.com/yelizariev/addons-yelizariev/blob/9.0/hidden_admin/security.xml#L4 
Rules cannot conflict. They can repeat each other. Which is not a big problem

**Comment by saltonmassally** [comment]
So I am guessing the most restrictive will take precedence?

**Comment by yelizariev** [comment]
So, seems you agree with my suggestion above:

> So, possible solution here is remove security rules from /saas_client/security/rules.xml files and add note about usefull modules to saas_client/README.rst

I just not sure to which README add these notes. Probably in a root Readme

**Comment by yelizariev** [comment]
> So I am guessing the most restrictive will take precedence?

To get access both rules must pass

**Comment by saltonmassally** [comment]
Yes the root Readme.. what are your thoughts on this?

**Comment by yelizariev** [comment]
I think put Note on root README or just put there a reference to some place where list of useful modules for saas client can be found.

**Comment by saltonmassally** [comment]
:+1: thanks for working on these
