### ISSUE TITLE
how to edit 'max user allowed' for clients?

### ISSUE THREAD

**Issue by clxadmin** [it-projects-llc/odoo-saas-tools#519]
Hello, how to edit 'max user allowed' for clients?

**Comment by 360org** [comment]
![image](https://cloud.githubusercontent.com/assets/8590556/25770534/4b37c63e-3262-11e7-9da3-b47f2efafed7.png)

**Comment by 360org** [comment]
chose the user number you want to add

**Comment by clxadmin** [comment]
this error / info happens if I try this user enhancement
![maxuser](https://cloud.githubusercontent.com/assets/9445285/25802916/d35ab380-33f4-11e7-9a4b-a8b295022dd5.png)

**Comment by iledarn** [comment]
@clxadmin, what version (8.0, 9.0, 10.0) are you testing?

**Comment by clxadmin** [comment]
@iledarn -- I'm running Version 10.0.

I found out that the user amount is set but not visible on SaaS Tool. After logging in to client I can see the new user amount to SaaS information. After relogin to SaaS Tools they also visible there.

So It is working....just not visible in the same time you send this parameters in SaaS Tool
