### ISSUE TITLE
Template DB inheritance Mechanism

### ISSUE THREAD

**Issue by saltonmassally** [it-projects-llc/odoo-saas-tools#52]
Template DBs can grow very complex but much to often I find out that I have 5 or so steps common with the setting up of these DB. I think a cool feature would be for template DB to inherit from another template DB... what are your thoughts on this and how best do you think it could be implemented

**Comment by yelizariev** [comment]
You can duplicate template database via built-in manage database tool. Then use it in saas_portal.plan (probably some minor fixes is needed here)
