### ISSUE TITLE
Security related addons to be ported to 8.0

### ISSUE THREAD

**Issue by saltonmassally** [it-projects-llc/odoo-saas-tools#58]
@yelizariev which of these are not compatible with 8.0

ir_rule_protected - makes impossible for non-superuser admin edit\delete protected ir.rule
access_restricted - makes impossible for administrator set (and see) more access rights (groups) than he already have. (follow the link for more description)
hidden_admin - makes admin (user and partner) invisible
access_apps - allows to have administrators which don't have access to Apps
access_settings_menu - allows to show settings menu for non-admin

**Comment by yelizariev** [comment]
I think only these:
access_settings_menu
access_apps
as they use 9.0 menus

**Comment by yelizariev** [comment]
@tarzan0820 if you will port these modules for 8.0, could you please send a Pull Request to addons-yelizariev repo

**Comment by saltonmassally** [comment]
sure, will do so
