### ISSUE TITLE
Deploying an AWS AMI Image on a new Domain

### ISSUE THREAD

**Issue by novatorapps** [it-projects-llc/odoo-saas-tools#583]
Hi. I have taken snapshot of Odoo SaaS instance and deployed it on a new domain. I can log into the individual dbs by renaming db.

ALTER DATABASE "template.domain.com" RENAME TO "template.newdomain.com";
#psql -U postgres -h aws-public-dns
#xv2MGgjHiv]8)mx 

sudo -su odoo
cd /var/lib/odoo/.local/share/Odoo/filestore

However, I can't log in as super admin using oauth from main main db because it is using previous domain. How can I update the client, template and saas server links in main db. 

Any help would be appreciated?

**Comment by 360org** [comment]
as i know saas not work like that

**Comment by bassn** [comment]
Hello,

 

For renaming DB, did you use SaaS tool feature in the menu

             SaaS >> Clients >> Button Rename Database  (in form view)

?

**Comment by novatorapps** [comment]
Thanks for replying guys. Yes- I tried changing the URLs of server, template db, and portal url in settings. When I try to rename the client dbs, it doesn't anything like I update the DB name and it stays the same

**Comment by njeudy** [comment]
@passion342 you can not duplicate existing installation on different domain.

For now it is not on the scope, feel free to propose a PR to do this, but I think it is better to deploy fresh install on new domain (you have to rename all servers, plan, etc ...)

I close this issue as it is not a bug or a problem with saas-tools. Actually new domain = new saas-tools installation / setup :)

thanks for your report,
