### ISSUE TITLE
Error while clicking the Create Client Button (Step 8) 

### ISSUE THREAD

**Issue by WalterArguello** [it-projects-llc/odoo-saas-tools#584]
Hi. I have Ubuntu 14.04.5 LTS, PostgreSQL 9.5, Odoo 9.0, Python 2.7.6.

I followed the instructions at https://github.com/Antiun/yelizariev-saas with the minimum changes.

I was able to advance successfully until step 7.

However, in step 8, the following error was generated, which I could not overcome.

File "/usr/local/src/odoo-extra-addons/it-projects-llc/odoo-saas-tools/saas_portal/wizard/config_wizard.py", line 133, in _default_name
    return plan.generate_dbname(raise_error=False)[0]
IndexError: string index out of range

I appreciate the guidance you can give me.

**Comment by 360org** [comment]
go to saas seting click apply then comeback with this step

**Comment by WalterArguello** [comment]
Hi W360S. Thanks for answering.
I went to Settings->SaaS Portal Settings->Apply
But behavior did not change.
