### ISSUE TITLE
idea how to impove SaasConfig

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#59]
Instead of field database_id in saas.config model

```
database_id = fields.Many2one('saas_portal.client', string='Database', default=_default_database_id)
```

it could be 

```
line_ids = fields.One2many('saas.config.line', string='Databases')
```

Where

```
SaasConfigLine(models.Model):
     base_id = fields.Many2one('saas.config')
     database_id = fields.Many2one('saas_portal.client', string='Database', default=_default_database_id)
```

So, administrator will be able to configure several database at once.

**Comment by saltonmassally** [comment]
I agree with you on this; as databases increase, configuring one at a time is going to be a pain.... we should also introducing tagging so you can search databases tagged with a particular tag and configure them in a batch

**Comment by saltonmassally** [comment]
@yelizariev I think this can be closed now
