### ISSUE TITLE
How to use restore database as database template?

### ISSUE THREAD

**Issue by minhyk** [it-projects-llc/odoo-saas-tools#598]
I got a trouble when using saas tools that I already have a database myself. How can I use it as database template?

**Comment by yelizariev** [comment]
The feature is not supported yet. Some suggestion can be found here: https://github.com/it-projects-llc/odoo-saas-tools/issues/249 (it's about client database, but template has to be very similar)

The feature is planned to be implemented in terms of Fundraising campaign: https://it-projects-llc.github.io/odoo-saas-tools/blog/fundraising-campaign
we are seeking for sponsors at the moment

**Comment by minhyk** [comment]
@yelizariev Many thanks for your answer. I will try it.
