### ISSUE TITLE
Does we need to add each database name/Client database name in /etc/hosts file

### ISSUE THREAD

**Issue by sathwiksunderreddy** [it-projects-llc/odoo-saas-tools#602]
Hi 

I have followed all the steps descrobed in settingup and configuring odoo Saas from 
"https://odoo-saas-tools.readthedocs.io/en/10.0/setup/install.html"
and I was successfully able to configure odoo in my local instance.

when I am trying to create a new plan with a new templatedb or create a new client(new database)

should i have to add the client database domain to /etc/hosts everytime and for every client who signup and for every client should it be done monually adding a to /etc/hosts file

I have noticed that if i add those domains to /etc/hosts file then only Iam able to login after creating a new client 
like 
127.0.0.1 client-x.DomainName
127.0.0.1 client-y.DomainName
127.0.0.1 client-z.DomainName

can I get any more info about this

and how can i control modules or apps installtion or installed apps on clients database from Server instance is there any prefered documentation to learn controlling apps or modules of clients from the Saas Server
@yelizariev 

Thanks in Advance

**Comment by ovnicraft** [comment]
I have the same doubt about this, considering odoo can use db based on host.

**Comment by njeudy** [comment]
@sathwiksunderreddy @ovnicraft 

saas installation heavy use domain name and database name. You have to setup a proxy and a dns setup to automate this. In use dnsmasq to redirect *.DomainName to 127.0.0.1

(I am on mac https://passingcuriosity.com/2013/dnsmasq-dev-osx/ but can be easy adapt to linux ;)

I close this issue as it is an dns setup issue not saas-tools .. 

Note to your question: the response is yes if you do it manually you have to add all entry in etc/hosts
