### ISSUE TITLE
[Odoo 10, Ubuntu 16.04] python process with 100% cpu

### ISSUE THREAD

**Issue by clxadmin** [it-projects-llc/odoo-saas-tools#621]
Hi
I have some 100% cpu processes from odoo like this with a long runtime:
![hig-python-process](https://user-images.githubusercontent.com/9445285/27835406-35625728-60db-11e7-8057-84f51a4707c2.png)

python /usr/local/src/odoo-source/odoo-bin --config=/etc/openerp-server.conf --logfile=/var/log/odoo/odoo-server.log

Has anyone any idea why the odoo-server.log create this high cpu load ?

**Comment by 360org** [comment]
depend on what you do in your server it sometimes have something like that.
if you reset your vps and check after 10 mins if average load around 1.x.x it will be ok, if it more then 5.x.x you need to check your system what are running hidden

**Comment by clxadmin** [comment]
ok.... restart server seems to stop some processes causing this cpu load. The question is where this processes come from. I will monitor it to find out
