### ISSUE TITLE
KeyError: 'login_success'

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#623]
Hello i have problems after separate odoo saas client to odoo stand alone system, when i try to login it show error 500 plz help

Traceback (most recent call last):
  File "/home/odoo/en-addons/website/models/ir_http.py", line 264, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/en-addons/website/controllers/main.py", line 84, in web_login
    if not redirect and request.params['login_success']=False:
KeyError: 'login_success'

**Comment by suv-appzbiz** [comment]
I am also facing the same error. Did you get any solution for this?

**Comment by njeudy** [comment]
hello @W360S @suv-appzbiz ,

Can you explain exactly "after separate odoo saas client to odoo stand alone system". what did you do.
In traceback there is no mention of saas-tools .. only odoo website ..

can you tell odoo version you use ?

**Comment by 360org** [comment]
You can try to separate odoo saas tools client to single odoo and try to log in :) it will show you problems. it for long time ago. i think i miss that problem

**Comment by njeudy** [comment]
did not understand why separate saas tools client ? on fresh odoo just setup oauth ?

**Comment by 360org** [comment]
mean separate saas client DB to single odoo
example your client they don't want to use your service they have their own server and ask you to set up for them single odoo.

**Comment by njeudy** [comment]
@W360S don't know if a correctly understand your need but if your customer does not want saas service, don't use saas-tools .. export database template (backup) and configure odoo from scratch ?

@yelizariev what do you think ?

**Comment by 360org** [comment]
that is situation :) of cause when you extract client DB to single odoo it will get whole content in :) if you open from scratch it will be blank DB. 
the problem comes when you extract DB to single odoo and it shows error when running single odoo

**Comment by njeudy** [comment]
ok :) so your customer was on your saas service database and now want to be on is own server ?

- You copy / backup database
- You import it on fresh server
- And have probleme to login

Can you post log errors when you import database .. think there is a dependency module problem and some did not load correctly.

**Comment by 360org** [comment]
I think the problems come when saas does not match with auth. I think I did solve someways like:
go to live saas client. uninstalled everything related to saas, then restore DB to a single one and it works. 
something like so. already pass for long :)

**Comment by njeudy** [comment]
Ok will close this one and feel free to open new one if probleme stay.

think we have to write clean doc for this spécific case.
