### ISSUE TITLE
Deep Base SaaS domain support

### ISSUE THREAD

**Issue by captainjapeng** [it-projects-llc/odoo-saas-tools#638]
My base domain is `xxx.yyy.com` and when logging in to a plan, I'm redirected to `template.yyy.com` instead of `template.xxx.yyy.com`.

**Comment by yelizariev** [comment]
@iledarn Can you answer how to manage such cases?

**Comment by njeudy** [comment]
@captainjapeng can you post screenshot of your base domain setup ?

Which odoo version you use ?

**Comment by captainjapeng** [comment]
I've used `itprojectsllc/install-odoo:10.0` image to test it back then. Sorry but I don't have the setup anymore.

**Comment by njeudy** [comment]
Ok thanks I close this issue, feel free to create new one if you encounter this issue with your tests.
