### ISSUE TITLE
Odoo 11 come out :)

### ISSUE THREAD

**Issue by 360org** [it-projects-llc/odoo-saas-tools#658]
Odoo 11 come out :) interested for saas :)

**Comment by necrodevz** [comment]
Me too!!!

**Comment by augustosamame** [comment]
I have installed a couple of propietary v10 modules in v11 and they installed and worked properly with no modifications. Have you tried just installing the v10 SaaS modules in v11 to check if they work, and if they fail, which errors are shown?

**Comment by 360org** [comment]
tell me what are they @augustosamame ? I know that 11 work python 3.0 and currently 10 work with 2.7 maybe some of the module will work :) we need to try :) especially Sales & CRM I like these feature :)

**Comment by njeudy** [comment]
@W360S 110. branch is available .. some work has to be donne but base is ok.

**Comment by njeudy** [comment]
See #746 to have clean V11.0 branch (WIP)
