### ISSUE TITLE
bash_profile permission denied error

### ISSUE THREAD

**Issue by hoangtuan151** [it-projects-llc/odoo-saas-tools#670]
Hi team,

Thanks for your works so much!

I've followed the guide from this link: "http://it-projects-llc.github.io/odoo-saas-tools/getting-started/" and got the "/root/.bash_profile: Permission denied" error at last step.

Pls help me. Thanks you!

Here's the details:

~$ INIT_SAAS_TOOLS_VALUE=' \
> --portal-create \
> --server-create \
> --plan-create \
> --odoo-script=/mnt/odoo-source/odoo-bin \
> --odoo-config=/mnt/config/odoo-server.conf \
> --portal-db-name=portal \
> --server-db-name=server-1 \
> --server-hosts-template={dbname}.{base_saas_domain_1} \
> --plan-template-db-name=template-1 \
> --plan-clients=demo-%i \
> ' && docker exec -u root -t odoo /bin/bash \
> -c "export INIT_SAAS_TOOLS='$INIT_SAAS_TOOLS_VALUE'; bash /install-odoo-saas.sh"
SYSTEM=supervisor
PLATFORM=unknown
OS_RELEASE=jessie
**-su: /root/.bash_profile: Permission denied**

2017-11-05 23:15:58
saas.py >>> Read odoo config, /mnt/config/odoo-server.conf

2017-11-05 23:15:58
saas.py >>> Waiting for port, 127.0.0.1, 8069

2017-11-05 23:15:58
saas.py >>> Port is used. Probably, odoo is already running. Let's try to use it. It it will fail, you need either stop odoo or pass another port to saas.py via --xmlrpc-port arg

2017-11-05 23:15:58
saas.py >>> create database via xmlrpc, portal

**Comment by CristianHR** [comment]
@hoangtuan151 You managed to solve the error, or someone who has succeeded please!, I have the same error

**Comment by ilmir-k** [comment]
@CristianHR Try to execute the script as root

**Comment by CristianHR** [comment]
@ilmir-k if I run as root, but I still get the error
