### ISSUE TITLE
Python error when installing odoo10

### ISSUE THREAD

**Issue by vkhalil** [it-projects-llc/odoo-saas-tools#686]
File "/mnt/addons/it-projects-llc/odoo-saas-tools/saas.py", line 319, in rpc_init_portal
    if not arg.get('dynamic_base_domain'):
NameError: global name 'arg' is not defined

There is a typo in saas.py line 319 arg instead of args

**Comment by yelizariev** [comment]
Fixed by @vkhalil in https://github.com/it-projects-llc/odoo-saas-tools/pull/688
