### ISSUE TITLE
Installation of saas_portal_async module, disables mailgun functionality

### ISSUE THREAD

**Issue by g3492** [it-projects-llc/odoo-saas-tools#705]
After installation of saas_portal_async module, there is no more mailgun functionality. Tested with odoo version 8.0.

I am not a developer, but I think there is some conflict/problem with create_new_database functions which are referenced in saas_sysadmin_mailgun, saas_portal_async and saas_portal modules.
Congratulation for the great work.

**Comment by njeudy** [comment]
hello @g3492 

As odoo did we do not support odoo V8 anymore, can you test in V10 version ?
If it is a real production probleme feel free to open an other issue with the error you have after checking it is the case in V10 or V11.

Thanks, for your report.
