### ISSUE TITLE
BUG Apple SAFARI

### ISSUE THREAD

**Issue by LiberTang0** [it-projects-llc/odoo-saas-tools#741]
When i try to connect with "Log in via SaaS" it redirect me to the homepage of the odoo  website but not the odoo backend.

It appears only with safari. 
I'm using odoo 8.

**Comment by njeudy** [comment]
@LiberTang0 I think you have a probleme with oauth saas setup in your saas-server instance. By default saas is pointing to odoo, you have to change this.

By the way we do not support odoo V8.0 anymore as odoo did and will not investigate more.
Think it is an odoo oauth issue.

Can you test with odoo V10 and saas-tools V10

Thanks for your report.
