### ISSUE TITLE
odoo problem

### ISSUE THREAD

**Issue by spectra10008** [it-projects-llc/odoo-saas-tools#742]
when i try to run odoo in linux ubuntu
Traceback (most recent call last):
File "./odoo-bin", line 5, in
import('pkg_resources').declare_namespace('odoo.addons')
ImportError: No module named pkg_resources

how can i solve it?

**Comment by 360org** [comment]
try that: sudo apt-get install --reinstall python-pkg-resources
if it help or 
pip install --upgrade setuptools
pip install --upgrade distribute 
hope that help
