### ISSUE TITLE
Error when run script to create portal, server, template Saas V 11

### ISSUE THREAD

**Issue by dawnblack2** [it-projects-llc/odoo-saas-tools#750]
When I run this script 
INIT_SAAS_TOOLS_VALUE=' \
--portal-create \
--server-create \
--plan-create \
--odoo-script=/mnt/odoo-source/odoo-bin \
--odoo-config=/mnt/config/odoo-server.conf \
--portal-db-name=portal \
--server-db-name=server-1 \
--server-hosts-template={dbname}.{base_saas_domain_1} \
--plan-template-db-name=template-1 \
--plan-clients=demo-%i \
' && docker exec -u root -t odoo /bin/bash \
-c "export INIT_SAAS_TOOLS='$INIT_SAAS_TOOLS_VALUE'; bash /install-odoo-saas.sh"

There are one error to show 
SYSTEM=upstart
PLATFORM=unknown
OS_RELEASE=trusty
-su: /root/.bash_profile: Permission denied

2018-03-15 06:22:46
saas.py >>> Read odoo config, /mnt/config/odoo-server.conf
Traceback (most recent call last):
  File "/mnt/addons/it-projects-llc/odoo-saas-tools/saas.py", line 134, in <module>
    odoo_config = get_odoo_config()
  File "/mnt/addons/it-projects-llc/odoo-saas-tools/saas.py", line 126, in get_odoo_config
    for (name, value) in p.items('options'):
  File "/usr/lib/python3.5/configparser.py", line 855, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 855, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 852, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 443, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%d$'

Please help me

**Comment by serpentcs-dev1** [comment]
@dawnblack2 I faced this same issue when I was configuring and creating saas instance, for me, it was showing because of the `--db-filter=^%h$` used in odoo config file!

Not sure what is the solution for this, later I just removed that parameter while creating saas system

**Comment by darshan-serpent** [comment]
@dawnblack2 I faced this same issue when I was configuring and creating saas instance, for me, it was showing because of the `--db-filter=^%h$` used in odoo config file!

Not sure what is the solution for this, later I just removed that parameter while creating saas system
