### ISSUE TITLE
how can i set the SaaS Code Colum?

### ISSUE THREAD

**Issue by keecome** [it-projects-llc/odoo-saas-tools#752]
@W360S 
@Englishrain

https://github.com/it-projects-llc/odoo-saas-tools/blob/11.0/docs/usage/subscriptions.rst

3: Go to the Sales >> Configuration >> Products >> Attributes

and set Saas code as

SUBSCRIPTION_PERIOD for Period

and

MAX_USERS for Number of users.

There you can also specify Type of selection Radio/Select for the website.

I can't configure these two fields?

**Comment by 360org** [comment]
@keecome still on progress it not release ithink

**Comment by njeudy** [comment]
@keecome will start to implement this in V11 for now it's not implemented .
