### ISSUE TITLE
saas_server.saas_oauth_provider

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#76]
I have a bad feeling about reference for oauth provider.
It's created in saas_server module

```
<data noupdate="1">
    <record id="saas_oauth_provider" model="auth.oauth.provider">
        <field name="name">SaaS</field>
        <field name="auth_endpoint">http://odoo.local/oauth2/auth</field>
        <field name="scope">userinfo</field>
        <field name="validation_endpoint">http://odoo.local/oauth2/tokeninfo</field>
        <field name="data_endpoint"></field>
        <field name="css_class">zocial openerp</field>
        <field name="body">Log in via SaaS Portal</field>
        <field name="enabled" eval="True"/>
    </record>
</data>
```

Then we copy it with the same ID to template DB:

```
        client_env['ir.model.data'].create({
            'name': 'saas_oauth_provider',
            'module': 'saas_server',
            'noupdate': True,
            'model': 'auth.oauth.provider',
            'res_id': oauth_provider.id,
        })
```

And then use it in Client database

```
_defaults = {
    'oauth_provider_id': lambda self,cr,uid,ctx=None: self.pool['ir.model.data'].xmlid_to_res_id(cr, SI, 'saas_server.saas_oauth_provider')
}
```

If someone occasionally install saas_server in template or client database and then uninstall one, the record saas_server.saas_oauth_provider would be deleted too.

**Comment by saltonmassally** [comment]
I understand your worry... maybe we should stop saas_server fro being installed on clients? Maybe have an ir.config.parameter record when available throws a warning we try installing saas_server...

**Comment by yelizariev** [comment]
I think we can add dummy auth.oauth.provider record in saas_client module with noupdate setting.

```
<data noupdate="1">
    <record id="saas_oauth_provider" model="auth.oauth.provider">
        <field name="name">SaaS</field>
    </record>
</data>
```

and then in saas_server/models/saas_server.py  update it:

```
     # copy auth provider from saas_server
     saas_oauth_provider = self.env.ref('saas_server.saas_oauth_provider')
     oauth_provider = None
     if is_template_db and not client_env.ref('saas_server.saas_oauth_provider', raise_if_not_found=False):
         oauth_provider_data = {'enabled': False, 'client_id': client_id}
         for attr in ['name', 'auth_endpoint', 'scope', 'validation_endpoint', 'data_endpoint', 'css_class', 'body', 'enabled']:
             oauth_provider_data[attr] = getattr(saas_oauth_provider, attr)

-            oauth_provider = client_env['auth.oauth.provider'].create(oauth_provider_data)
-            client_env['ir.model.data'].create({
-                'name': 'saas_oauth_provider',
-                'module': 'saas_server',
-                'noupdate': True,
-                'model': 'auth.oauth.provider',
-                'res_id': oauth_provider.id,
-            })
+            oauth_provider = client_env.ref('saas_client.saas_oauth_provider')
+            oauth_provider.write(oauth_provider_data)
```

i.e. we use saas_**server**.saas_oauth_provider in server and saas_**client**.saas_oauth_provider in client database

**Comment by serpentcs-dev1** [comment]
@yelizariev I guess I am facing this issue 

>  File "saas.py", line 199, in main
>     rpc_init_server(args.get('server_db_name'))
>   File "saas.py", line 337, in rpc_init_server
>     'auth_endpoint': oauth_provider.get('auth_endpoint').replace('odoo.local', portal_host),
> AttributeError: 'NoneType' object has no attribute 'get'



I could not get the oauth_provider :

 `oauth_provider = rpc_xmlid_to_object(auth, 'server_saas.saas_oauth_provider', 'auth.oauth.provider')`

Is there any current solution to this?

edit: My bad, I was doing some change in this file and somehow happened to mistype the module name `server_saas.saas_oauth_provider`
