### ISSUE TITLE
Use own domain for ecommerce

### ISSUE THREAD

**Issue by ovnicraft** [it-projects-llc/odoo-saas-tools#761]
Hi, i have deployed this tools for 10.0 so i want to know how implement if one customer needs use their own domain?

**Comment by njeudy** [comment]
Think you can setup proxy to point www.mydomain.com to saas_server instance, and rename customer database to www.mydomain.com ...

**Comment by 360org** [comment]
yep that for what i do, but not www :) because if you put www it understands is subdomain

**Comment by ovnicraft** [comment]
So i will try,

Thanks !
