### ISSUE TITLE
Odoo 12 and future of the project [$1,100]

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/odoo-saas-tools#805]
Dear users and contributors, thank you for interest and help! 

I'm glad to announce that the project is going to be split and remade almost from scratch in odoo 12.
New main repository: https://github.com/it-projects-llc/saas-addons

Key changes: 
* **No more *SaaS Server* via odoo**. We shall not reinvent the wheel. We can use kubernetes\rancher for that part.
* Multi-server deployment stuff will be moved to a separate repository: https://gitlab.com/itpp/saas-clusters -- it allows to split deployment issues with issues about saas modules 
* **saas_client** is not needed anymore. We will use xmlrpc or openapi to manage instance. Other features of the module will be moved to existing repository: https://github.com/it-projects-llc/access-addons/
* Some renamings. For example, *SaaS Portal* will be *Master Instance*, ``saas_portal_*`` --> ``saas_``
* General cleanup
* More powerfull CI tools for saas

Changes in ``saas_portal``:
* rename to ``saas``
* get rid of sale\trial part and keep only base technical things. 
* Changes in models. See *Models overview* section in [README file](https://github.com/it-projects-llc/saas-addons/pull/2/files#diff-571f0db9f09b50b6393bda8ef05d1a6c) (reviews and ideas are welcome)

**First release** is focused on simplified version of **saas_portal_demo**.  it's a module to demonstrate applications in apps.odoo.com.
**How it works now**
* When User clicks *Live Preview* he sees some page with demo info. 
* Then he clicks *Try Trial* button, which asks him to create account on *Portal*. 
* Then he gets an email with a url to access his instance.

**How it will work**
Once user clicks *Live Preview*, he is redirected to his demo instance immediatly, Then he sees message in Apps Switcher (similar to one in Odoo EE) _"database is expired in two hours, contact us if you need more time and any assistance"_

**odoo-saas-tools** will not have 12 branch and will be abandoned after some time.

cc @iledarn @njeudy @ilmir-k @blaggacao

**Comment by blaggacao** [comment]
For the affected or interested ones, there will be a viable alternative, once out of alpha: [The Odoo-Operator](https://xoe-labs.github.io/odoo-operator/)

**Comment by yelizariev** [comment]
@blaggacao I think the odoo-operator will be used. The idea of the project is to create odoo modules to manage databases via master odoo instance (send invoices, suspend when it's not paid, collect statistic, etc.)

**Comment by yelizariev** [comment]
![image](https://user-images.githubusercontent.com/186131/57510971-8391db80-7321-11e9-850f-e364c6dc333c.png)
Base module is released!
See
https://github.com/it-projects-llc/saas-addons/tree/12.0/saas
https://github.com/it-projects-llc/saas-addons/blob/12.0/saas/doc/index.rst

We continue work on "Live Preview" tool

**Comment by yelizariev** [comment]
For custom development contact us by email: saas@it-projects.info

**Comment by yelizariev** [comment]
A survey about most-wanted saas features: https://docs.google.com/forms/d/e/1FAIpQLSdcnVT5etxtp3ZmaZudrtiBM8LwdHa7tmY1KGrodhBT-Obadw/viewform?usp=sf_link

**Comment by RosaliePerron** [comment]
How can I help for this issue ?

**Comment by yelizariev** [comment]
It's almost done. We make release next week

**Comment by yelizariev** [comment]
Done! Check "Make new odoo instance" button here: https://odoo-saas.sh

**Comment by usmanfarzandali** [comment]
how to donate for this project other then paypal ? 
any other way pls

**Comment by ilmir-k** [comment]
@usmanfarzandali please send us email to saas@it-projects.info with an amount you are ready to donate and we will send you the corresponding invoice with the payment details.
Thanks in advance for supporting the project.

**Comment by herawais** [comment]
> For the affected or interested ones, there will be a viable alternative, once out of alpha: [The Odoo-Operator](https://xoe-labs.github.io/odoo-operator/)

Site not found

**Comment by ilmir-k** [comment]
> Done! Check "Make new odoo instance" button here: https://odoo-saas.sh

New website is https://saas.it-projects.info/
