### ISSUE TITLE
[12.0] [MIG] saas_server & saas_client

### ISSUE THREAD

**Issue by FFernandez-PlanetaTIC** [it-projects-llc/odoo-saas-tools#820]
Hi,

Although the project will be remade from scratch in v12.0 #805 , I think portals <= v11.0 should be able to work together with server and clients >=12.0.

We have migrated to v12.0 an tested:

- auth_oauth_check_client_id
- auth_oauth_ip
- saas_base
- saas_client
- saas_server
- saas_server_backup_ftp

The work is available in the repository of @PlanetaTIC :

https://github.com/PlanetaTIC/odoo-saas-tools/tree/12.0-MIG-saas_server_client

@it-projects-llc , we can make a PR if you create branch 12.0.

Regards!

**Comment by ilmir-k** [comment]
@FFernandez-PlanetaTIC 
Thanks for your work.

@yelizariev could you create branch 12.0 ?

**Comment by yelizariev** [comment]
Done
