### ISSUE TITLE
Help: Error while installing  SaaS Portal - /page/start and Saas Portal Sale

### ISSUE THREAD

**Issue by ebukoz** [it-projects-llc/odoo-saas-tools#90]
File "/thrive/thrive-server/openerp/addons/base/ir/ir_model.py", line 956, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: website.theme" while parsing None:6, near
<data inherit_id="website.theme" name="saas portal assets">
            <xpath expr="//link[@href='/website/static/src/css/website.css']" position="before">
                <link rel="stylesheet" href="/saas_portal_start/static/src/css/odoo.css" t-ignore="true"/>
            </xpath>
        </data>

**Comment by yelizariev** [comment]
fixed in 9.0-dev branch 
https://github.com/yelizariev/odoo-saas-tools/commit/15ccf137c84eb6e3747ead347df365834c3a7e35
